---
title: "Setting up your workspace"
weight: 7
date: '2018-10-24'
author: "Mitchell Stares"
output: blogdown::html_page
editor_options: 
  chunk_output_type: console
---
```{r knitr options, message=FALSE, warning=FALSE, include=FALSE}
library(knitr)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

There are very quick ways to open R and begin coding, however, having an organised, well-structured working directory in your computer can save you hours of hassle and make your code much easier to share. As biology and data science are becoming increasingly complex many are turning to computer intensive, coding based software (like **you!**). With this movement in data science and open access, having our code reproducible, transparent and understandable is key. So why not start off like that.

{{% notice note %}}
The first part of this tutorial follows many practices outlined in the fantastic ["Guide to Reproducible Code in Ecology and Evolution"](https://www.britishecologicalsociety.org/wp-content/uploads/2017/12/guide-to-reproducible-code.pdf) from the British Ecological Society. I strongly recommend reading this at some stage. 
{{% /notice %}}

## File system  
Before we jump into R, we are going to create a clean and managable folder system. 
{{% notice info %}}
Create a new folder in a location of your choosing (e.g. My Documents or Desktop) called **R-tutorials**  
{{% /notice %}}

This can be named anything you like, but try to keep it relevant and understandable (for future you).  

{{% notice info %}}
In this new folder, create a series of new folders called:  
- __data__  
- __doc__  
- __figs__  
- __output__  
- __R__  
{{% /notice %}}

Here is the basic outline for these folders:  
<ul>
  <li> The **data** folder if where you store your raw/input data </li> 
  <li> The **doc** folder is where you store the manuscript for the project </li>  
  <li> The **figs** folder is where all of your figures will be stored from the analyses </li>
  <li> The **output** folder is where you keep any intermediate datasets generated by your analysis, result reports etc. </li>  
  <li> The **R** folder is pretty self-explanatory but it is where we will store all of our R scripts, notebooks etc. </li>  
</ul>

Now, let's move on to the next step. 

