---
title: "Removing Items"
description: "Remove objects or datasets from the R environment"
author: "Mitchell Stares"
weight: 15
date: '2018-11-09'
output: blogdown::html_page
editor_options:
  chunk_output_type: console
---
```{r knitr options, message=FALSE, warning=FALSE, include=FALSE}
library(knitr)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```
```{r eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
weeds<-read.csv("../../../resources/datafiles/weeds.csv")
library(tidyverse)
weeds <- rename(weeds, flowers = flowers.m3)
frogsp<-read.csv("../../../resources/datafiles/frogs.csv", header=TRUE)
enviro<-read.csv("../../../resources/datafiles/frog_environmental.csv", header=TRUE)
```  

By now, we have quite a few objects in our R environment that aren't being used. The **remove()** command does exactly that....removes objects from the R environment. This helps for making things nice and tidy, specifically in our environment window. 

```{r echo=TRUE, eval=FALSE, message=FALSE, warning=FALSE}
remove(frogfull, froginner, enviro_filter) # Removes all three objects we just generated
```

Use this in the console to "one off" remove an item.  

... that's all, NEXT!
